### ISSUE TITLE
Obtaining sender or group number to reply

### ISSUE THREAD

**Issue by RPTOR** [Labfox/whatsfly#30]
Hi, 

I had scanned through the event_data object upon receiving message but unable to:-

1) Determine if a message is sent to a personal channel or group channel
2) Unable to obtain group id to reply

Are there any parameters or variables in the event_data which can help on this ?  

Thanks,

James

**Comment by Labfox** [comment]
At first sorry for the reply time, GitHub doesn't notify me of new issues

For 1: the ```messageSource``` field in ```info``` ends with @g.us for a group, @s.whatsapp.net for a personal channel
For 2: 

* for a group: in  ```33783798385:58@s.whatsapp.net in 120363298974463298@g.us```, the id is ```120363298974463298@g.us``` but you need to pass ```120363298974463298``` with group=True to the function.
* for a personal chat: in ```33783798385:58@s.whatsapp.net in 33695604742@s.whatsapp.net```, the destination id is ```33695604742@s.whatsapp.net```(so ```33695604742``` for the functions), and the sender is ```33783798385:58@s.whatsapp.net```(```33783798385:58``` for functions)

Also you can get the name of the person sending the text in the ```pushName``` field on ```info```.

**Comment by Labfox** [comment]
I will be trying to add better manipulation on the next update.

**Comment by RPTOR** [comment]
Thanks ! Found it out after testing as well.

Anyway, if you're updating the document, there is a the media path variable in your whatsapp.py file which needs to be populated in order to make it work - perhaps can update it in the documentation as well.

Sorry that I am not able to contribute as I just started off Python programming (after leaving the programming arena a long while)

**Comment by RPTOR** [comment]
Thanks !
