### ISSUE TITLE
sendDocument() doesn't retain original filename and extension

### ISSUE THREAD

**Issue by RPTOR** [Labfox/whatsfly#34]
When using the sendDocument method, the file output from the receiving end of whatsapp (to be Open/Save as) doesn't retain the original filename or extension. Instead, it will be downloaded something like "DOC-20240911-WA0001[1].dat"

**Comment by Labfox** [comment]
This is going to be added on v1.0.0

**Comment by RPTOR** [comment]
Thanks !
